export const enum EVENT_KEY {
  'CREATE_NEW_ARCHIVE' = 'CREATE_NEW_ARCHIVE',
  'SAVE_ARCHIVE' = 'SAVE_ARCHIVE',
  'UPLOAD_IMAGE' = 'UPLOAD_IMAGE',
  'CLEAR_ALL' = 'CLEAR_ALL',
  'ADD_SUCCESS' = 'ADD_SUCCESS',
  'ADD_FAIL' = 'ADD_FAIL',
  'SAVE_SUCCESS' = 'SAVE_SUCCESS',
  'SAVE_FAIL' = 'SAVE_FAIL',
  'DELETE_SUCCESS' = 'DELETE_SUCCESS',
  'DELETE_FAIL' = 'DELETE_FAIL',
}
