export const enum EVENT_KEY {
  'CREATE_NEW_ARCHIVE' = 'CREATE_NEW_ARCHIVE',
  'UPLOAD_IMAGE' = 'UPLOAD_IMAGE',
  'CLEAR_ALL' = 'CLEAR_ALL',
  'SAVE_SUCCESS' = 'SAVE_SUCCESS',
  'SAVE_FAIL' = 'SAVE_FAIL',
}
