export const enum EVENT_KEY {
  'CREATE_NEW_ARCHIVE' = 'CREATE_NEW_ARCHIVE',
  'SAVE_ARCHIVE' = 'SAVE_ARCHIVE',
  'UPLOAD_IMAGE' = 'UPLOAD_IMAGE',
  'CLEAR_ALL' = 'CLEAR_ALL',
  'SHOW_TOAST' = 'SHOW_TOAST',
  'SHOW_CONFIRM' = 'SHOW_CONFIRM',
}
