name: CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "client/**"

jobs:
  client-ci:
    strategy:
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest]
    defaults:
      run:
        working-directory: ./client

    name: Generate Client CI
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
